apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payroll
  template:
    metadata:
      labels:
        app: payroll
    spec:
      containers:
        - name: payroll
          image: dkhw/images:latest
          ports:
            - containerPort: 8080
